sylius_admin_drawing_field:
  resource: |
    alias: sylius_registration_drawing.drawing_field
    section: admin
    templates: "@SyliusAdmin\\Crud"
    except: ['show', 'create']
    redirect: update
    grid: sylius_admin_drawing_field
    permission: true
    vars:
        all:
            subheader: sylius_registration_drawing.ui.manage_fields_of_your_drawings
            templates:
                form: "@RegistrationDrawingBundle/Resources/views/Attribute/_form.html.twig"
        index:
            icon: cubes
  type: sylius.resource

sylius_admin_get_drawing_fields:
  path: /fields
  methods: [GET]
  defaults:
    _controller: sylius_registration_drawing.controller.drawing_field:renderFieldsAction
    template: "@RegistrationDrawingBundle/Resources/views/Field/fieldChoice.html.twig"

sylius_admin_render_field_forms:
  path: /field-forms
  methods: [GET]
  defaults:
    _controller: sylius_registration_drawing.controller.drawing_field:renderFieldValueFormsAction
    template: "@RegistrationDrawingBundle/Resources/views/Field/fieldValueForms.html.twig"
