sylius_admin_get_drawing_fields:
  path: /admin/drawing-fields/fields
  methods: [GET]
  defaults:
    _controller: akki.controller.drawing_field::renderFieldsAction
    template: "@AkkiSyliusRegistrationDrawingPlugin/Field/fields.html.twig"

