sylius_registration_drawing:
  resource: |
    alias: akki.registration_drawing
    templates: "@SyliusAdmin\\Crud"
    except: ['show']
    redirect: index
    grid: akki_admin_registration_drawing
    section: admin
    permission: true
    vars:
      all:
        subheader: sylius_registration_drawing.ui.manage_your_registration_drawings
        templates:
          form: "@AkkiSyliusRegistrationDrawingPlugin/_form.html.twig"
      index:
        icon: file alternate
  type: sylius.resource
