sylius_grid:
  grids:
    sylius_admin_drawing_field:
      driver:
        name: doctrine/orm
        options:
          class: "%sylius_registration_drawing.model.drawing_field.class%"
      sorting:
        position: asc
      fields:
        name:
          type: string
          label: sylius.ui.name
        equivalent:
          type: string
          label: sylius.ui.equivalent
        type:
          type: twig
          label: sylius.ui.type
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/label.html.twig"
        createdAt:
          type: datetime
          label: sylius.form.registration_drawing.created_at
          sortable: ~
          options:
            format: d-m-Y H:i
        updatedAt:
          type: datetime
          label: sylius.form.registration_drawing.updated_at
          sortable: ~
          options:
            format: d-m-Y H:i
      filters:
        name:
          type: string
          label: sylius.ui.name
      actions:
        main:
          create:
            type: create_product_attribute
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
