sylius_grid:
  grids:
    sylius_admin_registration_drawing:
      driver:
        name: doctrine/orm
        options:
          class: "%sylius_registration_drawing.model.registration_drawing.class%"
      sorting:
        updatedAt: desc
      fields:
        name:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.name
          sortable: ~
        format:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.format
          sortable: ~
        createdAt:
          type: datetime
          label: sylius_registration_drawing.form.registration_drawing.created_at
          sortable: ~
          options:
            format: d-m-Y H:i
        updatedAt:
          type: datetime
          label: sylius_registration_drawing.form.registration_drawing.updated_at
          sortable: ~
          options:
            format: d-m-Y H:i
      filters:
        name:
          type: string
          label: sylius.ui.name
          options:
            fields: [ name ]
      actions:
        main:
          create:
            type: create
        item:
          send:
            type: send
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
            options:
              link:
                route: sylius_admin_registration_drawing_bulk_delete
  templates:
    action:
      send: "@RegistrationDrawingBundle/Resources/views/Grid/Action/create.html.twig"
