services:
    akki_sylius_registration_drawing_bundle.admin.menu_builder:
        class: Akki\SyliusRegistrationDrawingBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
