sylius_resource:
    resources:
        sylius_registration_drawing.registration_drawing:
            driver: doctrine/orm
            classes:
                model: Akki\SyliusRegistrationDrawingBundle\Entity\RegistrationDrawing
                form: Akki\SyliusRegistrationDrawingBundle\Form\Type\RegistrationDrawingType
                controller: Akki\SyliusRegistrationDrawingBundle\Controller\RegistrationDrawingController
                repository: Akki\SyliusRegistrationDrawingBundle\Repository\RegistrationDrawingRepository

        sylius_registration_drawing.drawing_field:
            driver: doctrine/orm
            classes:
                model: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingField
                form: Akki\SyliusRegistrationDrawingBundle\Form\Type\DrawingFieldType
                controller: Akki\SyliusRegistrationDrawingBundle\Controller\DrawingFieldController

        sylius_registration_drawing.drawing_field_association:
            driver: doctrine/orm
            classes:
                model: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingFieldAssociation
                repository: Akki\SyliusRegistrationDrawingBundle\Repository\DrawingFieldAssociationRepository
