parameters:
  akki_sylius_registration_drawing.exportsediteur_fs: fs_exportsediteur
  akki.form.type.drawing_field.validation_groups: [ sylius, akki ]
  akki.form.type.drawing_field_association.validation_groups: [ sylius, akki ]
  akki.form.type.generated_file.validation_groups: [ sylius, akki ]
  akki.form.type.output_formats.validation_groups: [ sylius, akki ]
  akki.form.type.registration_drawing.validation_groups: [ sylius, akki ]

sylius_grid:
  templates:
    action:
      create_drawing_field: "@AkkiSyliusRegistrationDrawingPlugin/Field/create.html.twig"
  grids:
    akki_admin_drawing_field:
      driver:
        name: doctrine/orm
        options:
          class: "%akki.model.drawing_field.class%"
      sorting:
        position: asc
      fields:
        name:
          type: string
          label: sylius.ui.name
        equivalent:
          type: string
          label: sylius.ui.equivalent
        type:
          type: twig
          label: sylius.ui.type
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/label.html.twig"
        createdAt:
          type: datetime
          label: sylius.form.registration_drawing.created_at
          sortable: ~
          options:
            format: d-m-Y H:i
        updatedAt:
          type: datetime
          label: sylius.form.registration_drawing.updated_at
          sortable: ~
          options:
            format: d-m-Y H:i
      filters:
        name:
          type: string
          label: sylius.ui.name
      actions:
        main:
          create:
            type: create_product_attribute
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
    akki_admin_registration_drawing:
      driver:
        name: doctrine/orm
        options:
          class: "%akki.model.registration_drawing.class%"
      sorting:
        updatedAt: desc
      fields:
        name:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.name
          sortable: ~
        format:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.format
          sortable: ~
        periodicity:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.periodicity
          sortable: ~
        day:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.day
          sortable: ~
        send_mode:
          type: string
          label: sylius_registration_drawing.form.registration_drawing.send_mode
          sortable: ~
        createdAt:
          type: datetime
          label: sylius_registration_drawing.form.registration_drawing.created_at
          sortable: ~
          options:
            format: d-m-Y H:i
        updatedAt:
          type: datetime
          label: sylius_registration_drawing.form.registration_drawing.updated_at
          sortable: ~
          options:
            format: d-m-Y H:i
      filters:
        name:
          type: string
          label: sylius.ui.name
          options:
            fields: [ name ]
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
            options:
              link:
                route: akki_admin_registration_drawing_bulk_delete

sylius_resource:
  resources:
    akki.registration_drawing:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusRegistrationDrawingBundle\Entity\RegistrationDrawing
        repository: Akki\SyliusRegistrationDrawingBundle\Repository\RegistrationDrawingRepository
        form: Akki\SyliusRegistrationDrawingBundle\Form\Type\RegistrationDrawingType
        interface: Akki\SyliusRegistrationDrawingBundle\Entity\RegistrationDrawingInterface

    akki.drawing_field:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingField
        repository: Akki\SyliusRegistrationDrawingBundle\Repository\DrawingFieldRepository
        form: Akki\SyliusRegistrationDrawingBundle\Form\Type\DrawingFieldType
        controller: Akki\SyliusRegistrationDrawingBundle\Controller\DrawingFieldController
        interface: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingFieldInterface

    akki.drawing_field_association:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingFieldAssociation
        repository: Akki\SyliusRegistrationDrawingBundle\Repository\DrawingFieldAssociationRepository
        interface: Akki\SyliusRegistrationDrawingBundle\Entity\DrawingFieldAssociationInterface

    akki.generated_file:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusRegistrationDrawingBundle\Entity\GeneratedFile
        repository: Akki\SyliusRegistrationDrawingBundle\Repository\GeneratedFileRepository
        interface: Akki\SyliusRegistrationDrawingBundle\Entity\GeneratedFileInterface
    akki.output_formats:
        driver: doctrine/orm
        classes:
            model: Akki\SyliusRegistrationDrawingBundle\Entity\OutputFormats
            repository: Akki\SyliusRegistrationDrawingBundle\Repository\OutputFormatsRepository
            interface: Akki\SyliusRegistrationDrawingBundle\Entity\OutputFormatsInterface

knp_gaufrette:
  adapters:
    exportsediteur:
      local:
        directory: "%kernel.project_dir%/var/exportsEditeur"
        create: true
  filesystems:
    fs_exportsediteur:
      adapter: exportsediteur
