akki_admin_registration_drawing:
    resource: "routing/registration_drawing.yaml"

akki_admin_drawing_field:
    resource: "routing/drawing_field.yaml"

akki_admin_generated_file:
    resource: "routing/generated_file.yaml"
