imports:
    - { resource: services/controller.yaml }
    - { resource: services/event_listener.yaml }
    - { resource: services/form.yaml }

services:
    Akki\SyliusRegistrationDrawingBundle\Menu\RegistrationDrawingFormMenuBuilder:
        arguments: [ '@knp_menu.factory', '@event_dispatcher']
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: sylius.admin.registration_drawing_form }

    Akki\SyliusRegistrationDrawingBundle\Service\ExportService:
        arguments: []
        tags:
            - { name: controller.service_arguments }

    Akki\SyliusRegistrationDrawingBundle\Command\ExportDrawingsCommand:
        arguments:
            - '@sylius_registration_drawing.repository.registration_drawing'
            - '@sylius.repository.order'
            - '@odiseo_sylius_vendor_plugin.repository.vendor'
            - '@sylius_registration_drawing.controller.registration_drawing'
            - '@App\Service\ExportEditeur\GeneratedFileService'
            - '@kernel'
        tags: [ 'console.command' ]
